'use client';
import { useCallback, useEffect, useRef, useState } from 'react';
import { Dialog, DialogContent, DialogDescription, DialogTitle } from '@/components/ui/dialog';
import { outfits, nightmares, person, smallGoat, snowFriends, vignette, type Outfit } from './pixels';
import Soundtrack from './Soundtrack';

const achievementList=[
 {id:'nightwardrobe',name:'The night shift',description:'Try all six after-hours outfits.',hint:'The wardrobe gets bigger when the moon comes out.',icon:'moon'},
 {id:'amygdala',name:'Oh, Amygdala. Oh, hello.',description:'Make friends with the thing on the roof.',hint:'Something is watching the garden under the Blood Moon. Say hello.',icon:'heart'},
 {id:'bloodmoon',name:'You have gained Insight',description:'Find the Blood Moon. The whole page felt it.',hint:'The moon has another side. Try it again after dark.',icon:'moon'},
 {id:'moon',name:'Just five more minutes',description:'Turn on the little night sky.',hint:'The moon in the illustration looks clickable. It is.',icon:'moon'},
 {id:'letter',name:'This one’s for you',description:'Find the note Idan left for you.',hint:'There’s something folded into the signature at the bottom.',icon:'letter'},
 {id:'snow',name:'Special delivery',description:'Nunu and Willump brought a snowball. Indoors.',hint:'Someone is waiting beside Microsoft Excel’s name.',icon:'snow'},
 {id:'stars',name:'Pocket full of stars',description:'Catch all three golden fireflies after dark.',hint:'Switch on the moon. Three little lights are waiting to be caught.',icon:'star'},
 {id:'pet',name:'Peer reviewed',description:'Pet the other GOAT.',hint:'The little goat at the bottom looks underappreciated.',icon:'goat'},
 {id:'wardrobe',name:'In every universe',description:'Try all eight daytime versions of Hodaya.',hint:'A change of outfit is cheaper than a new save file.',icon:'star'},
 {id:'java',name:'A threat, removed',description:'Put Main.java where it belongs.',hint:'The desktop has a very specific problem.',icon:'file'},
 {id:'leon',name:'Completely normal about him',description:'Inspect the Leon photo three times.',hint:'Surely that photograph is only worth one look.',icon:'heart'},
 {id:'rewind',name:'This action will have consequences',description:'Catch the blue butterfly.',hint:'Something blue has landed near the photographs.',icon:'butterfly'},
 {id:'eras',name:'Her lucky number',description:'Find the little 13 in her Eras outfit.',hint:'Try her Eras outfit, then look beside the little stage.',icon:'star'},
 {id:'teemo',name:'Suspicious landscaping',description:'Find Teemo’s contribution to the garden.',hint:'Look closely at the little scene. That mushroom is not decorative.',icon:'mushroom'},
 {id:'radahn',name:'Let the record show',description:'I would prefer not to be tagged in this. — Radahn',hint:'Someone may wish to dispute the historical record.',icon:'sword'},
];
type Notice={name:string;description:string;achievement?:boolean};
type Stored={version:1;outfit:Outfit;unlocked:string[];tried:Outfit[];javaDeleted:boolean;leonCount:number};
const storageKey='hodaya-little-world-v1';
function PixelIcon({type,className=''}:{type:string;className?:string}){
 const paths:Record<string,string>={
 heart:'M3 4h4v2h2V4h4v2h2v5h-2v2h-2v2H9v2H7v-2H5v-2H3v-2H1V6h2z',
 star:'M7 1h3v5h5v3h-5v5H7V9H2V6h5z',
 sword:'M12 1h4v4h-2v2h-2v2h-2v2h2v2h-2v-1H8v2H6v2H3v-3h2v-2h2V9H5V7h2v2h2V7h2V5h1z',
 music:'M6 2h9v3H9v8H7v2H3v-2H1v-3h2V8h3zM11 8h4v5h-2v2h-4v-2h-1v-3h3z',
 mushroom:'M5 2h6v2h3v3h2v4h-5v5H6v-5H1V7h2V4h2z',
 file:'M3 1h8v2h2v2h2v12H3zM5 9v1h7V9zM5 12v1h7v-1z',
 butterfly:'M1 3h4v2h2v3h2V5h2V3h4v6h-2v2h2v3h-4v-2H9v4H7v-4H5v2H1v-3h2V9H1z',
 goat:'M3 8h7V5h2V2h2v4h2v6h-3v2h-2v3H9v-3H5v3H3v-3H1V9h2z',
 sound:'M1 7h3V5h2V3h3v13H6v-2H4v-2H1zM12 5h2v2h2v5h-2v2h-2v-2h2V7h-2z',
 trophy:'M4 1h9v3h3v6h-3v2h-2v3h3v2H3v-2h4v-3H5v-2H2V4h2zM4 6H3v2h2zM13 6v2h1V6z',
 trash:'M2 4h14v2H2zM6 1h6v2H6zM4 7h10v9H4z',
 moon:'M9 1h4v2h-3v2H8v6h2v2h5v-2h2v3h-2v2H7v-2H4v-3H2V6h2V3h3V1z',
 letter:'M1 3h16v12H1zM3 5v2h2V5zM5 7v2h2V7zM7 9v2h4V9zM11 7v2h2V7zM13 5v2h2V5z',
 snow:'M7 0h3v5l3-3 2 2-4 3h6v3h-6l4 3-2 2-3-4v6H7v-6l-3 4-2-2 4-3H0V7h6L2 4l2-2 3 3z',
 };
 return <svg className={`pixel-icon ${className}`} viewBox="0 0 18 18" aria-hidden="true" shapeRendering="crispEdges"><path fill="currentColor" fillRule="evenodd" d={paths[type]||paths.star}/></svg>;
}
function Sprite({outfit,scene=false,hearts=false,goat=false,night=false,snow=false,bloodMoon=false,amygdalaHappy=false}:{outfit:Outfit;scene?:boolean;hearts?:boolean;goat?:boolean;night?:boolean;snow?:boolean;bloodMoon?:boolean;amygdalaHappy?:boolean}){
 const ref=useRef<HTMLCanvasElement>(null);
 useEffect(()=>{const canvas=ref.current;if(!canvas)return;const ctx=canvas.getContext('2d');if(!ctx)return;let id=0,last=0;const reduced=matchMedia('(prefers-reduced-motion: reduce)');let visible=true;const observer=new IntersectionObserver(([e])=>{visible=e.isIntersecting});observer.observe(canvas);const render=(now:number)=>{if(visible&&now-last>100){last=now;ctx.clearRect(0,0,canvas.width,canvas.height);ctx.imageSmoothingEnabled=false;const t=reduced.matches?1:now/1000;if(snow)snowFriends(ctx,t);else if(goat)smallGoat(ctx,t);else if(scene)vignette(ctx,outfit,t,hearts,night,bloodMoon,amygdalaHappy);else person(ctx,outfit,t,0,0,1,false,bloodMoon)}id=requestAnimationFrame(render)};id=requestAnimationFrame(render);return()=>{cancelAnimationFrame(id);observer.disconnect()}},[outfit,scene,hearts,goat,night,snow,bloodMoon,amygdalaHappy]);
 return <canvas ref={ref} width={snow?96:goat?48:scene?280:48} height={snow?64:goat?40:scene?250:72} className={scene?'vignette':'sprite'} aria-label={snow?'Nunu and Willump rolling a very large snowball':goat?'A tiny pixel-art goat':`${outfits.find(o=>o.id===outfit)?.name} outfit, drawn as a blonde Hodaya pixel sprite${bloodMoon?', cute nightmare version':''}`}/>;
}
export default function Tribute(){
 const [outfit,setOutfit]=useState<Outfit>('hunter');
 const [unlocked,setUnlocked]=useState<string[]>([]),[tried,setTried]=useState<Outfit[]>(['hunter']);
 const [notice,setNotice]=useState<Notice|null>(null),[modal,setModal]=useState<'achievements'|'leon'|'letter'|null>(null);
 const [javaDeleted,setJavaDeleted]=useState(false),[leonCount,setLeonCount]=useState(0);
 const [hearts,setHearts]=useState(false),[rewinding,setRewinding]=useState(false),[ready,setReady]=useState(false),[dragging,setDragging]=useState(false);
 const [saveAvailable,setSaveAvailable]=useState(true);
 const [amygdalaHappy,setAmygdalaHappy]=useState(false),[amygdalaPats,setAmygdalaPats]=useState(0);
 const [bloodMoon,setBloodMoon]=useState(false),[moonReveal,setMoonReveal]=useState(false);
 const [night,setNight]=useState(false),[caught,setCaught]=useState<number[]>([]),[delivery,setDelivery]=useState(0),[snowing,setSnowing]=useState(false);
 const [musicActive,setMusicActive]=useState(false),[musicPlaying,setMusicPlaying]=useState(false);
 const soundtrackAnchor=useRef<HTMLDivElement>(null),heroArt=useRef<HTMLDivElement>(null);
 const [saving,setSaving]=useState(false),[saveMessage,setSaveMessage]=useState('');
 const prevOutfit=useRef<Outfit>('hunter'),toastTimer=useRef<ReturnType<typeof setTimeout>|null>(null),effectTimers=useRef<ReturnType<typeof setTimeout>[]>([]);
 const current=outfits.find(o=>o.id===outfit)!;
 const nightmare=nightmares[outfit];
 const state=useRef({outfit,unlocked,tried,javaDeleted,leonCount});state.current={outfit,unlocked,tried,javaDeleted,leonCount};
 useEffect(()=>{try{const saved=JSON.parse(localStorage.getItem(storageKey)||'null');if(saved?.version===1){if(outfits.some(o=>o.id===saved.outfit)){setOutfit(saved.outfit);if(outfits.find(o=>o.id===saved.outfit)?.night)setNight(true)}if(Array.isArray(saved.unlocked))setUnlocked(saved.unlocked.filter((id:unknown)=>achievementList.some(a=>a.id===id)));if(Array.isArray(saved.tried))setTried(saved.tried.filter((id:unknown)=>outfits.some(o=>o.id===id)));setJavaDeleted(saved.javaDeleted===true);setLeonCount(Number.isFinite(saved.leonCount)?Math.max(0,saved.leonCount):0);}}catch{setSaveAvailable(false)}setReady(true);return()=>{if(toastTimer.current)clearTimeout(toastTimer.current);effectTimers.current.forEach(clearTimeout);}},[]);
 useEffect(()=>{if(!ready)return;try{const value:Stored={version:1,...state.current};localStorage.setItem(storageKey,JSON.stringify(value))}catch{setSaveAvailable(false)}},[outfit,unlocked,tried,javaDeleted,leonCount,ready]);
 const show=useCallback((n:Notice)=>{setNotice(n);if(toastTimer.current)clearTimeout(toastTimer.current);toastTimer.current=setTimeout(()=>setNotice(null),6000)},[]);
 const earn=useCallback((id:string)=>{if(state.current.unlocked.includes(id))return false;state.current.unlocked=[...state.current.unlocked,id];setUnlocked(state.current.unlocked);const a=achievementList.find(a=>a.id===id)!;show({...a,achievement:true});return true},[show]);
 const equip=useCallback((id:Outfit)=>{if(!outfits.some(o=>o.id===id))return;if(id===state.current.outfit)return;prevOutfit.current=state.current.outfit;setOutfit(id);state.current.outfit=id;const next=[...new Set([...state.current.tried,id])];state.current.tried=next;setTried(next);if(outfits.filter(o=>!o.night).every(o=>next.includes(o.id)))earn('wardrobe');if(outfits.filter(o=>o.night).every(o=>next.includes(o.id)))earn('nightwardrobe');if(outfits.find(o=>o.id===id)?.night)setNight(true)},[earn]);
 const deleteJava=useCallback(()=>{setJavaDeleted(true);setDragging(false);if(!earn('java'))show({name:'Correctly filed.',description:'Java remains exactly where it belongs.'})},[earn,show]);
 const actions=useRef({equip});actions.current={equip};
 useEffect(()=>{type ModelContext={registerTool:(tool:object,options:{signal:AbortSignal})=>Promise<void>|void};const context=(document as Document&{modelContext?:ModelContext}).modelContext;if(!context?.registerTool)return;const life=new AbortController();const register=(tool:object)=>{try{void Promise.resolve(context.registerTool(tool,{signal:life.signal})).catch(()=>{})}catch{}};register({name:'read_hodaya_wardrobe',title:'Read Hodaya’s wardrobe',description:'Read the selected outfit and local achievement progress.',inputSchema:{type:'object',properties:{},additionalProperties:false},annotations:{readOnlyHint:true},execute:()=>({outfit:state.current.outfit,available:outfits.map(o=>({id:o.id,name:o.name})),achievements:state.current.unlocked})});register({name:'equip_hodaya_outfit',title:'Change Hodaya’s outfit',description:'Equip a pixel-art outfit using the same switcher as the page. May unlock the wardrobe achievement locally.',inputSchema:{type:'object',properties:{outfit:{type:'string',enum:outfits.map(o=>o.id)}},required:['outfit'],additionalProperties:false},annotations:{readOnlyHint:false},execute:async(input:unknown)=>{const v=input as {outfit?:unknown};if(!v||typeof v.outfit!=='string'||!outfits.some(o=>o.id===v.outfit))throw new Error('Choose a listed outfit.');actions.current.equip(v.outfit as Outfit);await new Promise<void>(r=>requestAnimationFrame(()=>requestAnimationFrame(()=>r())));return {outfit:state.current.outfit}}});return()=>life.abort()},[]);
 function chooseOutfit(id:Outfit){equip(id);setSaveMessage('');if(matchMedia('(max-width: 760px)').matches)requestAnimationFrame(()=>requestAnimationFrame(()=>heroArt.current?.scrollIntoView({block:'start',behavior:matchMedia('(prefers-reduced-motion: reduce)').matches?'instant':'smooth'})))}
 async function saveHodaya(){
  if(saving)return;setSaving(true);setSaveMessage('');
  try{const source=document.createElement('canvas');source.width=64;source.height=88;const c=source.getContext('2d');if(!c)throw new Error('Canvas unavailable');person(c,outfit,1,8,8,1,false,bloodMoon);
   const output=document.createElement('canvas');output.width=384;output.height=528;const ctx=output.getContext('2d');if(!ctx)throw new Error('Canvas unavailable');ctx.imageSmoothingEnabled=false;ctx.drawImage(source,0,0,output.width,output.height);
   const blob=await new Promise<Blob>((resolve,reject)=>output.toBlob(value=>value?resolve(value):reject(new Error('Image unavailable')),'image/png'));
   const url=URL.createObjectURL(blob),link=document.createElement('a');link.href=url;link.download=`hodaya-${outfit}${bloodMoon?'-nightmare':''}.png`;document.body.appendChild(link);link.click();link.remove();setTimeout(()=>URL.revokeObjectURL(url),60000);setSaveMessage('Your little Hodaya is ready to keep.');
  }catch{setSaveMessage('Couldn’t save that one. Try again?')}finally{setSaving(false)}
 }
 function luckyNumber(){setHearts(true);effectTimers.current.push(setTimeout(()=>setHearts(false),3500));if(!earn('eras'))show({name:'13. Obviously.',description:'A lucky charm for her hitless era.'})}
 function photograph(){const n=leonCount+1;setLeonCount(n);setModal('leon');if(n>=3)earn('leon')}
 function rewind(){setRewinding(true);const previous=prevOutfit.current;prevOutfit.current=outfit;setOutfit(night&&!bloodMoon&&!outfits.find(o=>o.id===previous)?.night?'doll':previous);if(outfits.find(o=>o.id===previous)?.night)setNight(true);effectTimers.current.push(setTimeout(()=>setRewinding(false),1100));if(!earn('rewind'))show({name:'This seems familiar.',description:'Your previous outfit, one little moment ago.'})}
 function pet(){setHearts(true);effectTimers.current.push(setTimeout(()=>setHearts(false),3200));if(!earn('pet'))show({name:'A professional courtesy.',description:'Two GOATs. No competition.'})}
 function toggleMoon(){if(bloodMoon){setBloodMoon(false);setNight(false);setCaught([]);if(current.night){setOutfit('hunter');state.current.outfit='hunter'}show({name:'Morning, eventually.',description:'The website is cute again. You saw nothing.'});return}if(night){setBloodMoon(true);setMoonReveal(true);earn('bloodmoon');effectTimers.current.push(setTimeout(()=>setMoonReveal(false),4500));return}setNight(true);equip('doll');setCaught([]);earn('moon')}
 function catchStar(index:number){const next=[...new Set([...caught,index])];setCaught(next);if(next.length===3){earn('stars');setHearts(true);effectTimers.current.push(setTimeout(()=>setHearts(false),4500))}}
 function sendSnowball(){setDelivery(v=>v+1);setSnowing(true);effectTimers.current.push(setTimeout(()=>setSnowing(false),7000));if(!earn('snow'))show({name:'Another delivery.',description:'Nunu has directions. Willump has a snowball. Nothing can go wrong.'})}
 function openLetter(){setModal('letter');earn('letter')}
 function toggleSoundtrack(){const next=!musicActive;setMusicActive(next);if(next){soundtrackAnchor.current?.scrollIntoView({behavior:matchMedia('(prefers-reduced-motion: reduce)').matches?'instant':'smooth',block:'center'})}}
 return <div className={`tribute ${rewinding?'rewinding':''} ${bloodMoon?'blood-moon':''}`}>
  <header className="site-header"><a className="wordmark" href="#top" aria-label="Hodaya, back to top"><PixelIcon type="heart"/><span className="wordmark-domain">hodayazamiristhegoat.com</span></a><nav aria-label="Page navigation"><a href="#little-things">About Hodaya</a><button className="sound-button" onClick={toggleSoundtrack} aria-label={musicActive?'Pause background music':'Play background music'} aria-pressed={musicActive}><PixelIcon type="music"/><span>{musicPlaying?'Music on':musicActive?'Music…':'Play music'}</span></button><button className="achievement-button" onClick={()=>setModal('achievements')}><PixelIcon type="trophy"/><span>{unlocked.length} / {achievementList.length}</span><span className="sr-only"> achievements</span></button></nav></header>
  <main id="top">
   <section className="hero" aria-labelledby="hero-title">
    <div className="hero-copy"><p className="little-intro"><span className="tiny-star">✦</span> A little corner of the internet, just for you.</p><h1 id="hero-title">Hodaya is<br/>the GOAT<span className="title-dot">.</span></h1><p className="hero-description">She beat Promised Consort Radahn hitless.<br/>She studies IT. She has <em>opinions</em> about Java.<br/>This felt like it needed its own website.</p><div className="hero-footnote"><span className="drawn-arrow">↳</span><span>yes, Idan bought this domain</span></div><a href="#wardrobe" className="wardrobe-link">Same Hodaya. Different universe.<span aria-hidden="true">↓</span></a></div>
    <div className="hero-art" ref={heroArt} style={{'--scene-color':current.bg} as React.CSSProperties}>
     <div className="art-top-note">{bloodMoon?"she’s seen worse, honestly":"a tiny Hodaya has appeared"} <span aria-hidden="true">↴</span></div>
     <div className="art-scene"><Sprite outfit={outfit} scene hearts={hearts} night={night} bloodMoon={bloodMoon} amygdalaHappy={amygdalaHappy}/>{bloodMoon&&<button className="scene-amygdala" aria-label="Say hello to the little Amygdala" title="Oh, hello." onClick={()=>{setAmygdalaHappy(true);setAmygdalaPats(v=>v+1);effectTimers.current.push(setTimeout(()=>setAmygdalaHappy(false),4500));if(!earn('amygdala'))show({name:amygdalaPats>2?'It lives here now.':'Amygdala likes you.',description:amygdalaPats>2?'Idan bought the domain. Apparently it came with a tenant.':'Six arms. All asking for another pat.'})}}/>}<button className={`scene-moon ${night?'moon-on':''}`} aria-label={bloodMoon?'Return to daylight':night?'Look closer at the moon':'Turn on the night sky'} aria-pressed={night} onClick={toggleMoon} title="Stay a little longer"/>{night&&[0,1,2].filter(i=>!caught.includes(i)).map(i=><button key={i} className={`catchable-star star-${i}`} onClick={()=>catchStar(i)} aria-label={`Catch golden firefly ${i+1}`}><PixelIcon type="star"/></button>)}{outfit==='eras'&&<button className="lucky-thirteen" onClick={luckyNumber} aria-label="Inspect the lucky 13 charm"><span>13</span></button>}<button className="scene-mushroom" aria-label="Inspect the tiny mushroom" onClick={()=>{if(!earn('teemo'))show({name:'120,175 mastery points.',description:'Teemo insists this is decorative landscaping.'})}} title="A suspicious little mushroom"/><button className="scene-character" aria-label="Give pixel Hodaya a little heart" onClick={()=>{setHearts(true);effectTimers.current.push(setTimeout(()=>setHearts(false),3200));}}/></div>
     <div className="equipped-caption" aria-live="polite"><span className="caption-dash"/>{bloodMoon?nightmare.title:current.title}<span className="caption-dash"/></div><p className="outfit-quip">{bloodMoon?nightmare.quip:current.quip}</p>{bloodMoon&&<button className="daybreak-button" onClick={toggleMoon}>Back to the nice weather ↺</button>}<div className="keepsake-actions"><button className="keepsake-button" onClick={saveHodaya} disabled={saving}>{saving?'Getting her ready…':'Keep this little Hodaya'} <span aria-hidden="true">↓</span></button><a className="back-to-wardrobe" href="#wardrobe">Back to outfits ↑</a></div><p className="save-message" role="status">{saveMessage}</p>
    </div>
   </section>
   <section className="wardrobe" id="wardrobe" aria-label="Hodaya’s pixel wardrobe"><div className="wardrobe-heading"><span>{bloodMoon?"Pick her next nightmare":"Pick her next incarnation"}</span><p>{bloodMoon?"each one is having a different kind of night.":"same face. excellent taste in every timeline."}</p></div>{(!night||bloodMoon)&&<div className="outfit-lineup" role="group" aria-label="Choose Hodaya’s outfit">{outfits.filter(o=>!o.night).map(o=><button key={o.id} className={`outfit-choice ${o.id===outfit?'selected':''}`} onClick={()=>chooseOutfit(o.id)} aria-pressed={o.id===outfit} aria-label={`Wear ${o.name} outfit`}><span className="sprite-perch"><Sprite outfit={o.id} bloodMoon={bloodMoon}/><span className="selection-spark" aria-hidden="true">✦</span></span><span className="outfit-name">{o.name}</span><span className="outfit-game">{o.game}</span></button>)}</div>}{night&&<div className={`night-wardrobe ${!bloodMoon?'night-only':''}`}><div className="night-wardrobe-heading"><PixelIcon type="moon"/><span>{bloodMoon?'The rest of the nightmare':'The night shift'}</span><p>oh, you thought that was everyone?</p></div><div className="outfit-lineup night-lineup" role="group" aria-label="Hodaya’s night outfits">{outfits.filter(o=>o.night).map(o=><button key={o.id} className={`outfit-choice ${o.id===outfit?'selected':''}`} onClick={()=>chooseOutfit(o.id)} aria-pressed={o.id===outfit} aria-label={`Wear ${o.name} outfit`}><span className="sprite-perch"><Sprite outfit={o.id} bloodMoon={bloodMoon}/><span className="selection-spark" aria-hidden="true">✦</span></span><span className="outfit-name">{o.name}</span><span className="outfit-game">{o.game}</span></button>)}</div></div>}<div className="wardrobe-bottom"><span><span className="status-dot"/> {current.game}, but make it Hodaya.</span><span>{night?"Six more outfits. She stays busy.":"A few more come out after dark."}</span></div></section>
   <section className="little-things" id="little-things" aria-labelledby="evidence-title"><div className="section-intro"><span className="tiny-star">✦</span><h2 id="evidence-title">A few things about Hodaya.</h2><p>A small collection of her greatest hits.</p></div><div className="scrapbook">
     <div className="photo-stack"><span className="tape tape-one"/><button className="polaroid" onClick={photograph} aria-label="Inspect Hodaya and Leon’s photograph"><img src="/photos/hodaya-leon.jpg" alt="Hodaya’s mirror photo with a portrait of Leon Kennedy in the corner" width="1320" height="1468" loading="lazy"/><span>her type? classified.</span></button><div className="photo-note">a completely normal<br/>amount of admiration <span>↖</span></div><button className="blue-butterfly" aria-label="Catch the blue butterfly" onClick={rewind}><PixelIcon type="butterfly"/></button></div>
     <article className="radahn-paper"><div className="paper-heading"><PixelIcon type="sword"/><span>OFFICIAL INCIDENT REPORT</span><span>No. 000</span></div><h3>Promised Consort Radahn<br/>vs. Hodaya</h3><div className="verdict"><div className="zero">0<span>hits taken</span></div><div className="verdict-text">I still don't know how she did this.<br/><strong>Radahn probably doesn't either.</strong></div></div><div className="stamp">HITLESS<br/><span>VERIFIED BY REALITY</span></div><p className="incident-note">Two swords. A meteor. A whole second phase.<br/>All that, just to become a footnote on her website.</p><button className="underlined" onClick={()=>{if(!earn('radahn'))show({name:'Radahn’s official statement',description:'“I would prefer not to be tagged in this.”'})}}>Request a comment from Radahn <span aria-hidden="true">↗</span></button></article>
     <aside className="real-life"><div className="mini-photo"><img src="/photos/hodaya.jpg" alt="Hodaya sitting on stone steps beside pink flowers" width="649" height="793" loading="lazy"/><span className="tape tape-two"/></div><p>the person responsible<br/>for all this nonsense.</p><div className="league-tag"><button className="snow-stamp" onClick={sendSnowball} aria-label="Ask Nunu and Willump for a delivery"><Sprite outfit="lux" snow/></button><div><a href="https://op.gg/lol/summoners/eune/Microsoft%20Excel-daya" target="_blank" rel="noreferrer">Microsoft Excel<span>#daya · EUNE ↗</span></a></div></div><p className="league-small">Nunu main energy.<br/>Teemo-shaped liability.<br/>An alarming amount of Lux.</p></aside>
    </div></section>
   <section className="desktop-section" aria-labelledby="desktop-title"><div className="desktop-copy"><h2 id="desktop-title">One small bug<br/>in the universe.</h2><p>She can survive the Lands Between.<br/>The college syllabus is another story.</p><span className="hand-note">you know what to do →</span></div><div className={`tiny-desktop ${dragging?'is-dragging':''}`}><div className="desktop-titlebar"><span><PixelIcon type="file"/> hodaya’s desktop</span><span>— &nbsp; □ &nbsp; ×</span></div><div className="desktop-interior"><div className="desktop-file-place">{!javaDeleted?<button className="desktop-file" draggable onDragStart={e=>{e.dataTransfer.setData('text/plain','Main.java');setDragging(true)}} onDragEnd={()=>setDragging(false)} onClick={()=>show({name:'Main.java',description:'A getter for the getter. Put it in the bin. You can drag it, or just click the bin.'})}><PixelIcon type="file"/><span>Main.java</span><small>cursed artifact</small></button>:<div className="file-gone"><PixelIcon type="star"/><span>inner peace restored.</span><button onClick={()=>{setJavaDeleted(false);show({name:'A questionable decision.',description:'Java has returned. The bin remains available.'})}}>undo, for some reason</button></div>}</div><button className={`recycle-bin ${javaDeleted?'full':''}`} aria-label={javaDeleted?'Java is in the recycle bin':'Put Main.java in the recycle bin'} onClick={deleteJava} onDragOver={e=>e.preventDefault()} onDrop={e=>{e.preventDefault();if(e.dataTransfer.getData('text/plain')==='Main.java')deleteJava()}}><PixelIcon type="trash"/><span>{javaDeleted?'where it belongs':'recycle bin'}</span></button></div><div className="desktop-status"><span>{javaDeleted?'1 threat removed. 0 regrets.':'Main.java → recycle bin'}</span><span>IT dept.</span></div></div></section>
  </main>
  <div ref={soundtrackAnchor} id="soundtrack"><Soundtrack active={musicActive} onActiveChange={setMusicActive} onPlayback={setMusicPlaying}/></div>
  <footer className="site-footer"><div className="footer-doodle"><button onClick={pet} aria-label="Pet the little goat"><Sprite outfit="hunter" goat/></button><div><button className="idan-signature" onClick={openLetter}><PixelIcon type="letter"/><span>From Idan, with love.</span></button></div></div><div className="footer-secrets"><p>There are a few secrets here.<br/><button onClick={()=>setModal('achievements')}>{unlocked.length} of {achievementList.length} found. Keep being nosy.</button></p></div></footer>
  <div className="domain-footer"><span>hodayazamiristhegoat.com</span></div>
  {bloodMoon&&<div className="blood-motes" aria-hidden="true">{Array.from({length:15},(_,i)=><i key={i} style={{left:`${(i*71)%100}%`,animationDelay:`-${i*1.7}s`,animationDuration:`${12+i%5*3}s`}}/>)}</div>}
  {moonReveal&&<div className="moon-reveal" role="status"><span>✧</span><strong>The Blood Moon rises.</strong><p>Hodaya seems remarkably unbothered.</p><button onClick={()=>setMoonReveal(false)}>Of course she is.</button></div>}
  {snowing&&<div className="snow-delivery" key={delivery} aria-hidden="true"><Sprite outfit="lux" snow/><span>special delivery for Microsoft Excel</span></div>}
  {notice&&<div className={`achievement-toast ${notice.achievement?'earned':''}`} role="status"><span className="toast-icon"><PixelIcon type={notice.achievement?'trophy':'star'}/></span><div><small>{notice.achievement?'ACHIEVEMENT UNLOCKED':'A SMALL DISCOVERY'}</small><strong>{notice.name}</strong><p>{notice.description}</p></div><button onClick={()=>setNotice(null)} aria-label="Dismiss notification">×</button></div>}
  <Dialog open={modal!==null} onOpenChange={open=>{if(!open)setModal(null)}}><DialogContent className={modal==='leon'?'relic-dialog photo-dialog':modal==='letter'?'relic-dialog letter-dialog':'relic-dialog'} showCloseButton={false}><button className="dialog-dismiss" onClick={()=>setModal(null)} aria-label="Close dialog">×</button>{modal==='letter'?<><DialogTitle className="sr-only">פתק להודיה</DialogTitle><DialogDescription className="sr-only">מאת עידן</DialogDescription><div className="idan-letter" lang="he" dir="rtl"><span className="letter-spark one" aria-hidden="true">✧</span><span className="letter-spark two" aria-hidden="true">✧</span><div className="letter-goat" aria-hidden="true"><Sprite outfit="hunter" goat/></div><p><span className="letter-big">את <em>הגואט</em> טווין</span><span className="letter-small">מגיע לך לשמוע את זה</span></p><span className="letter-heart" aria-hidden="true"><PixelIcon type="heart"/></span></div></>:modal==='leon'?<><DialogTitle>{leonCount>=3?'Okay, this is a shrine now.':'A completely normal photograph.'}</DialogTitle><DialogDescription className="dialog-description">{leonCount>=3?'Fine. We made him a shrine.':'A mirror selfie. One small Leon. Nothing to investigate.'}</DialogDescription><div className={`leon-exhibit ${leonCount>=3?'shrine-mode':''}`}><img src="/photos/hodaya-leon.jpg" alt="Hodaya with Leon S. Kennedy pictured beside her" width="1320" height="1468"/>{leonCount>=3&&<div className="shrine-hearts" aria-hidden="true">{Array.from({length:9},(_,i)=><PixelIcon key={i} type="heart"/>)}</div>}</div><p className="leon-caption">{leonCount>=3?'Budget for roof repairs: denied. Budget for Leon: approved.':leonCount===2?'You looked again. The frame seems to be getting more expensive.':'The frame appears to be hiding something. Perhaps another look.'}</p><button className="dialog-action" onClick={photograph}>{leonCount>=3?'One more look':'Look a little closer'}</button></>:<><DialogTitle>Awards for being nosy.</DialogTitle><DialogDescription className="dialog-description">{unlocked.length} of {achievementList.length} tiny discoveries. No grinding required.</DialogDescription><div className="achievement-ledger">{achievementList.map(a=><div key={a.id} className={unlocked.includes(a.id)?'achievement-row complete':'achievement-row'}><PixelIcon type={unlocked.includes(a.id)?a.icon:'star'}/><div><h3>{unlocked.includes(a.id)?a.name:'An undiscovered little thing'}</h3><>{unlocked.includes(a.id)?<p>{a.description}</p>:<details className="secret-hint"><summary>Show a hint</summary><p>{a.hint}</p></details>}</></div><span>{unlocked.includes(a.id)?'✓':'?'}</span></div>)}</div><p className="local-save-note">{saveAvailable?'Your discoveries are remembered on this browser.':'Discoveries work, but this browser is not allowing saves.'}</p></>}</DialogContent></Dialog>
 </div>;
}
